CREATE TABLE IF NOT EXISTS account_requests (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  full_name VARCHAR(150) NOT NULL,
  email VARCHAR(150) NOT NULL,
  office_id INT UNSIGNED NOT NULL,
  id_photo_path VARCHAR(255) NULL,
  id_photo_original_name VARCHAR(255) NULL,
  id_photo_mime VARCHAR(150) NULL,
  id_photo_size BIGINT UNSIGNED NULL,
  status ENUM('pending','approved','rejected') NOT NULL DEFAULT 'pending',
  requested_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  reviewed_at DATETIME NULL,
  reviewed_by INT UNSIGNED NULL,
  rejection_reason VARCHAR(500) NULL,
  approved_user_id INT UNSIGNED NULL,
  PRIMARY KEY (id),
  KEY idx_account_requests_status (status),
  KEY idx_account_requests_email (email),
  KEY idx_account_requests_office_id (office_id),
  KEY idx_account_requests_reviewed_by (reviewed_by),
  CONSTRAINT fk_account_requests_office FOREIGN KEY (office_id) REFERENCES offices (id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_account_requests_reviewed_by FOREIGN KEY (reviewed_by) REFERENCES users (id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT fk_account_requests_approved_user FOREIGN KEY (approved_user_id) REFERENCES users (id) ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
